dist: bionic
sudo: true
language: python
python:
- 3.6.8
services:
- docker
before_install:
- sudo -E apt-get -yq --no-install-suggests --no-install-recommends install postgresql-11
  postgresql-client-11
- sudo -E sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
- sudo -E sed -i 's/port = 5433/port = 5432/' /etc/postgresql/*/main/postgresql.conf
- sleep 10
- sudo -E service postgresql stop 10
- sudo -E ps axuwww | grep -i postg
- if [ ! -d /var/ramfs/postgresql/11/main ]; then sudo -u postgres /usr/lib/postgresql/11/bin/initdb
  -D /var/ramfs/postgresql/11/main; fi
- sudo -E systemctl -l restart postgresql@11-main
- sudo -E systemctl -l status postgresql@11-main
before_script:
- psql -U postgres -c "CREATE USER connect WITH PASSWORD 'connect';"
- psql -U postgres -c "ALTER ROLE connect WITH SUPERUSER;"
- psql -U connect postgres -c "CREATE DATABASE connect;"
install:
- pip install pipenv
- pipenv install --system --dev
- pip install coveralls
env:
  global:
  - SECRET_KEY=SK
  - DEFAULT_DATABASE="postgres://connect:connect@localhost:5432/connect"
  - OIDC_RP_SERVER_URL=
  - OIDC_RP_REALM_NAME=
  - OIDC_RP_CLIENT_ID=
  - OIDC_RP_CLIENT_SECRET=
  - OIDC_OP_AUTHORIZATION_ENDPOINT=
  - OIDC_OP_TOKEN_ENDPOINT=
  - OIDC_OP_USER_ENDPOINT=
  - OIDC_OP_JWKS_ENDPOINT=
  - OIDC_RP_SIGN_ALGO=
  - OIDC_OP_LOGOUT_ENDPOINT=
  - BILLING_COST_PER_WHATSAPP=0.0
  - BILLING_TEST_MODE=True
  - secure: ieMkT/FKlgSfWxQu44utmkBBSKpSp27Cxg0k4SapA1WZg+2lxxSVo5C0kuyso6Shb8vhP8cNbphnP/LfCjlWrcjd/XwnRFhPYark1m2qd54XPWVmdnBeOJdMAM1gb27gHi9n15cKXkyX6LjYLvTs6IFj4q4Im+ywNDWmm3xXP2uKC9KexR/29bjtVQH9Vqx2Jx4Zuzqkkhwz90kLmJM3G706MtCro9tx5RiJxjClAeA1Hbc4BO2Gm74Q6lIfBBdB+PmyK4NrpasvI4pKactM+7sMxKZ5jGoDvTt1UQnOHADl7jLTkxoNNoO3Z3Ri2Q8LmSs7pDBr4XChnqNfsvEi8dqezRK5lVsHPpwpCQ7EfPfdW+ermd1VMMbvEzRKEUxy0WL3q7AP+ZazJWAS8rLIQnZbtcnBHJYaFfLvcKeyt5k9LgVAWUx3EQA/WkSs1YMAV7YATQYKbHZIWlyRvxbdGDICN9v9OwZaifEuKSoQnlF8soWyns5Be4gBvZeKKu7uQ50+xwGQErgEr8bzeymeeVy3YGjDZyE38an6hZFT4P1y9ieGYyTRWwPs9TjC1DaTYiLlrH3zZgT2Rx9GtN95J5Io7MNcsPZ2Gfbkmm1Gtzf0cY8d8PGifkvf/gniPiNCR/fUXDBHicq/FUnx8kUs3SJOFiLU9twSt4q5reIIOew=
script:
- python manage.py migrate
- python manage.py collectstatic --noinput
- flake8
- travis_wait coverage run manage.py test
after_success:
- coveralls
