# use container-based Ubuntu Trusty
dist: bionic
sudo: true

language: python
python:
  - "3.6.8"

services:
  - docker

install:
  - pip install pipenv
  - pipenv install --system --dev
  - pip install coveralls

env:
  global:
    - SECRET_KEY=SK
    - OIDC_RP_SERVER_URL=
    - OIDC_RP_REALM_NAME=
    - OIDC_RP_CLIENT_ID=
    - OIDC_RP_CLIENT_SECRET=
    - OIDC_OP_AUTHORIZATION_ENDPOINT=
    - OIDC_OP_TOKEN_ENDPOINT=
    - OIDC_OP_USER_ENDPOINT=
    - OIDC_OP_JWKS_ENDPOINT=
    - OIDC_RP_SIGN_ALGO=
    - OIDC_OP_LOGOUT_ENDPOINT=

script:
  - make createproto
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - flake8
  - travis_wait coverage run manage.py test

after_success:
  - coveralls
