dist: bionic
sudo: true
language: python
python:
- 3.6.8
services:
- docker
before_install:
- sudo -E apt-get -yq --no-install-suggests --no-install-recommends install postgresql-11
  postgresql-client-11
- sudo -E sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
- sudo -E sed -i 's/port = 5433/port = 5432/' /etc/postgresql/*/main/postgresql.conf
- sleep 10
- sudo -E service postgresql stop 10
- sudo -E ps axuwww | grep -i postg
- if [ ! -d /var/ramfs/postgresql/11/main ]; then sudo -u postgres /usr/lib/postgresql/11/bin/initdb
  -D /var/ramfs/postgresql/11/main; fi
- sudo -E systemctl -l restart postgresql@11-main
- sudo -E systemctl -l status postgresql@11-main
before_script:
- psql -U postgres -c "CREATE USER connect WITH PASSWORD 'connect';"
- psql -U postgres -c "ALTER ROLE connect WITH SUPERUSER;"
- psql -U connect postgres -c "CREATE DATABASE connect;"
install:
- pip install pipenv
- pipenv install --system --dev
- pip install coveralls
env:
  global:
  - SECRET_KEY=SK
  - DEFAULT_DATABASE="postgres://connect:connect@localhost:5432/connect"
  - OIDC_RP_SERVER_URL=
  - OIDC_RP_REALM_NAME=
  - OIDC_RP_CLIENT_ID=
  - OIDC_RP_CLIENT_SECRET=
  - OIDC_OP_AUTHORIZATION_ENDPOINT=
  - OIDC_OP_TOKEN_ENDPOINT=
  - OIDC_OP_USER_ENDPOINT=
  - OIDC_OP_JWKS_ENDPOINT=
  - OIDC_RP_SIGN_ALGO=
  - OIDC_OP_LOGOUT_ENDPOINT=
  - BILLING_COST_PER_WHATSAPP=0.0
  - BILLING_TEST_MODE=True
  - secure: "Ho5GMvPwgeQPvmds9J9gN1AEnf7Y2240uRrmoFML+TRhFok9rzPVcb1TvIsTlOPf/RQnc2qHkbMkDHEFoO2EXlB9qN+TEWihaasv2HRr2jIVwYNRz8ZAp6B88NAXbjIKUeyp8Zc0ZpYOuJ4HSR/WjeaIjfRdcDcb6vaqCq7XRMj51kgByhKjdb73wE7zsVRw7OdysbuL5dwRzVwI5Sor0RieLYNFjfQ0+6rCb1sYL8Fg9fNR5t6G8Yfl6oisuWEt04ox9D48/Fz/wjkVYh8RSksxra6Y9LEGzAzNDy4oVptfilWOdbNiiCPaZUBDNO+X9/gOUcJmOOVbLObollfjuFxk/artfwQWeJLEzKakiLVG6+jjxohP0Dtz4mVgbpcMLE5DOdxMwFGfPWLuIMPvzcvgGoz9RDGJEpapPpN5qrHWKO/KAAgcGL7g1zQei2uAm0FKojUCZ6fToyGP3r1Hb03JlgGqQCS6OofsDG6IH05+OfTXj2NFPzYzgGIuaGoSm7RiK8+hfMQFLD1Egza9mgTpa9j/xe8xMKD9DQkiTxWEVnAkZ3wEGaA+GLHDarDzW2UxL29F22LnGd/1Ik47xM3y+7Jh+3IweDvJJlQsvd8eNrRji3/9A6Gw5XbTQWMb6nbFa/Vl8fve0OKAolt/mR7ZWNlI87vtqO8LGT2CMTs="
script:
- python manage.py migrate
- python manage.py collectstatic --noinput
- flake8
- travis_wait coverage run manage.py test
after_success:
- coveralls
